### ISSUE TITLE
Incompatibility with Skyrim AE 1.6.640 and SKSE64 2.4.4

### ISSUE THREAD

**Issue by dunwiddie** [ersh1/TrueHUD#1]
Reported by SKSE Plugin Loader:

> A DLL plugin has failed to load correctly. If a new version of Skyrim was just released, the plugin needs to be updated. Please check the mod's webpage for details.
> 
> TrueHud.dll: disabled, only compatible with versions earlier than 1.6.629
>
> Continuing to load may result in lost save data or other undesired behavior.

Default HUD is used when this can't load.

**Comment by ersh1** [comment]
Fixed in 1.1.7
