### ISSUE TITLE
Incompatibility with Skyrim SSE v1.6.1130

### ISSUE THREAD

**Issue by ghost** [ersh1/TrueHUD#5]
Mod is causing CTD on the main menu screen.

Extracted from CrashLogger:
> Skyrim SSE v1.6.1130
> CrashLoggerSSE v1-11-1-0 Nov 18 2023 13:56:33
> 
> Unhandled exception "EXCEPTION_ACCESS_VIOLATION" at 0x7FFA58C05C6F TrueHUD.dll+0035C6F	mov edx, [rax+rcx*4]

Full changelog here if that can help: [https://pastebin.com/uw2nJcbM](https://pastebin.com/uw2nJcbM)

**Comment by ersh1** [comment]
Fixed in 1.1.9
